upstream server_upstream {
  server server:3000;
}

upstream client_upstream {
  server client:80;
}

server {
  listen 80;
  server_name _;

  client_max_body_size 50m;

  gzip on;
  gzip_types text/plain text/css application/json application/javascript text/javascript application/xml image/svg+xml;
  gzip_min_length 1024;

  # Backend API
  location /api/ {
    proxy_pass http://server_upstream;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # Client (Nginx serving static)
  location / {
    proxy_pass http://client_upstream;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
